### ISSUE TITLE
[Suggestion]: Different Pet-Variants through petshop

### ISSUE THREAD

**Issue by DoctaEnkoda** [Jakllp/MyPet#59]
# Feature request

Axolotls always have the same variant, Give the possibility of having different axolots.

## Describe the solution you'd like

Add Variant in Database

**MyPet Build/Version:** 3.12-RC4

**Comment by Jakllp** [comment]
How did you create/get the axolotls?

**Comment by DoctaEnkoda** [comment]
in petshop

**Comment by Jakllp** [comment]
The MyPet-petshop has always given you just one variant of a given pet (same with horse, parrot, rabbit etc)
You can get different axolotl variants throught the `/petadmin create` command or other plugins.

This might be added in the future

**Comment by Jakllp** [comment]
This is actually already possible:
https://wiki.mypet-plugin.de/setup/configurations/pet-shops.yml
Under Options:
"These work exaclty like the parameters for the pet create admin command." -> you can create a multiple axolotls that have different names and different variants under "option" (variants are numeric so 0-4)

**Comment by DoctaEnkoda** [comment]
Strangely, it doesn't work.

**Comment by Jakllp** [comment]
Can you send what you put into the file?

**Comment by DoctaEnkoda** [comment]
Yes :
```yml
      axolotl_rare:
        Name: Axolotl
        Description:
          - <green>It's a Axolotl!
        PetType: Axolotl
        EXP: 0
        Price: 1000
        Options:
            - "variant:4"
            - "name:test"
```
